# General Jekyll Config
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, vendor]
highlighter: rouge

plugins:
  - jekyll-sitemap

permalink: /:categories/:title/

collections:
  toplevel:
    output: true
    permalink: '/:path/'
  workshops:
    output: true
  documentation:
    output: true
    permalink: '/doc/:path/'

markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  syntax_highlighter_opts:
    line_numbers: 
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class
