addgroup "CS1"
addsubgroup "Basic API Calls"
addassignment "27-GameGridBasic"
addassignment "56-2DIndexing"

addsubgroup "Tests and Conditions"
addassignment "34-GameTutorials"
addassignment "19-Bugstomp"
addassignment "45-ExplorerRobot"
addassignment "78-Thresholding"

addsubgroup "Loops"
addassignment "25-Patterns"
addassignment "23-MountainPaths"
addassignment "33-AudioMixing"
addassignment "52-AudioWave"
addassignment "56-2DIndexing"
addassignment "55-FrequencyPlayer"
addassignment "68-MusicNotes"
addassignment "65-Reddit"
addassignment "37-SubsamplingBitdepth"
addassignment "62-Flags"
addassignment "67-ControlsTutorialThree"
addassignment "78-Thresholding"

addsubgroup "Input/Output"
addassignment "10-HurricaneTracker"
addassignment "72-PixelDrawing"
addassignment "68-MusicNotes"
addassignment "55-FrequencyPlayer"
addassignment "61-Flight-Data"
addassignment "84-Energy"
addassignment "85-ForestCov"

addsubgroup "1D Arrays"
addassignment "33-AudioMixing"
addassignment "55-FrequencyPlayer"
addassignment "68-MusicNotes"
addassignment "65-Reddit"
addassignment "70-WordleBot"
addassignment "37-SubsamplingBitdepth"
addassignment "78-Thresholding"

addsubgroup "2D Arrays"
addassignment "6-GridSquareFill"
addassignment "7-GridLyrics"
addassignment "16-ImagePuzzle"
addassignment "40-ImageProcessing"
addassignment "56-2DIndexing"
addassignment "52-AudioWave"
addassignment "71-PiEstimation"
addassignment "45-ExplorerRobot"
addassignment "74-Fractals"
addassignment "62-Flags"

addsubgroup "Games"
addassignment "17-ControlsTutorial"
addassignment "18-ControlsTutorialTwo"
addassignment "67-ControlsTutorialThree"
addassignment "11-2048Game"
addassignment "13-InfiniteRunner"
addassignment "20-Minesweeper"
addassignment "21-RaceCar"
addassignment "22-Snake"
addassignment "32-TicTacToe"
addassignment "36-Pong"
addassignment "35-ConnectFour"
addassignment "41-SpaceInvaders"
addassignment "69-SnakeQueue"
addassignment "45-ExplorerRobot"

addsubgroup "Audio"
addassignment "55-FrequencyPlayer"
addassignment "52-AudioWave"
addassignment "33-AudioMixing"
addassignment "68-MusicNotes"
addassignment "37-SubsamplingBitdepth"
addassignment "78-Thresholding"

addsubgroup "Simulation"
addassignment "14-SpreadingFire"
addassignment "15-FallingSand"

addsubgroup "Data Encoding"
addassignment "73-ColorEncoding"
addassignment "37-SubsamplingBitdepth"

addgroup "Data Structures"
addsubgroup "LinkedList"
addassignment "1-ListIMDB"
addassignment "2-ListEQ"

addsubgroup "Stacks and Queues"
addassignment "12-AStarMaze"
addassignment "26-TowersOfHanoi"
addassignment "22-Snake"
addassignment "69-SnakeQueue"

addsubgroup "Recursion"
addassignment "26-TowersOfHanoi"
addassignment "74-Fractals"
addassignment "75-KochCurve"
addassignment "76-Zcurve"

addsubgroup "Trees"
addassignment "5-BST_Earthquakes"
addassignment "8-PQBook"
addassignment "24-ImageCompressionKdTree"
addassignment "39-BookDistance"
addassignment "60-Quadtree-CityData"

addsubgroup "Hashing, Hash Tables, and Hash Maps"
addassignment "8-PQBook"
addassignment "39-BookDistance"
addassignment "84-Energy"
addassignment "85-ForestCov"

addsubgroup "Graphs"
addassignment "12-AStarMaze"
addassignment "3-GraphBaconNumber"
addassignment "30-TemporalBaconNumber"
addassignment "4-GraphEQ"
addassignment "9-ShortestPathOSM"
addassignment "31-TemporalPageRank"
addassignment "39-BookDistance"
addassignment "66-Chess-Data"


addgroup "Algorithms"
addsubgroup "Big Oh"
addassignment "28-BigOhMatters"

addsubgroup "Sorting"
addassignment "29-SortingBenchmark"

addsubgroup "Brute Force"
addassignment "64-Voronoi_Diagram"

addsubgroup "Divide and Conquer"
addassignment "59-ConvexHull_CityData"

addsubgroup "Search space"
addassignment "70-WordleBot"
addassignment "12-AStarMaze"
addassignment "9-ShortestPathOSM"
addassignment "23-MountainPaths"

addsubgroup "Complexity of Graph Problems"
addassignment "9-ShortestPathOSM"
addassignment "30-TemporalBaconNumber"
addassignment "31-TemporalPageRank"

addsubgroup "Spanning Tree"
addassignment "44-MST-Cities"

addsubgroup "Spatial Problems"
addassignment "43-SpatialIndexing"
addassignment "59-ConvexHull_CityData"
addassignment "60-Quadtree-CityData"

addsubgroup "Greedy Algorithms"
addassignment "23-MountainPaths"
addassignment "9-ShortestPathOSM"
addassignment "38-GeologicalSurvey"
addassignment "44-MST-Cities"

addsubgroup "Dynamic Programing"
addassignment "23-MountainPaths"
addassignment "9-ShortestPathOSM"

addsubgroup "NP-Complete problems"
addassignment "38-GeologicalSurvey"

addsubgroup "Multi objective optimization"
addassignment "23-MountainPaths"
