WINDOWTITLE = 'BRIDGES 2.1(Java Version)'
DOCTITLE = 'BRIDGES 2.1(Java Version)'
HEADER = '<b>BRIDGES 2.1(Java Version)</b>'
SRCDIR = './v21/'
TARGET:
	javadoc -sourcepath $(SRCDIR) \
	-overview ./overview.html \
	-d ./bridges \
	-windowtitle $(WINDOWTITLE) \
	-doctitle $(DOCTITLE)  \
	-header $(HEADER)  \
	./v21/base/*.java ./v21/connect/*.java ./v21/data_src_dependent/*.java ./v21/validation/*.java



