WINDOWTITLE = 'BRIDGES 2.1(Java Version)'
DOCTITLE = 'BRIDGES 2.1(Java Version)'
HEADER = '<b>BRIDGES 2.1(Java Version)</b>'
SRCDIR = '/Users/krs/gr/bridges/bridges7-15/src/main/java/edu/uncc/cs/bridges_v21'
TARGET:
	javadoc -sourcepath $(SRCDIR) \
	-overview ./overview.html \
	-d . \
	-windowtitle $(WINDOWTITLE) \
	-doctitle $(DOCTITLE)  \
	-header $(HEADER)  \
	$(SRCDIR)/base/*.java $(SRCDIR)/connect/*.java $(SRCDIR)/data_src_dependent/*.java $(SRCDIR)/validation/*.java



